[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter = +<*> -<logging_tests/host/>
build_type = debug          ; usually enough
; or (more complete but slower)
; build_flags = -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

lib_deps = 
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
    adafruit/Adafruit BMP3XX Library@^2.1.6
    hideakitai/ArduinoEigen@^0.3.2
    mikalhart/TinyGPSPlus@^1.1.0
    okalachev/MAVLink@^2.0.26
lib_extra_dirs =
    lib
lib_ignore =
    mavlink

build_flags =
    -I lib/mavlink/generated/include
    -Wno-address-of-packed-member
